"""
City configs, search queries, and signal keyword lists.
"""

CITIES = {
    "boston": {
        "label": "Boston, MA",
        "state": "MA",
        "search_terms": [
            "physical therapy Boston MA",
            "cash pay physical therapy Boston MA",
            "out of network physical therapy Boston MA",
            "direct access physical therapy Boston MA",
        ],
        "choosept_location": "Boston, MA",
        "choosept_lat": "42.3600825",
        "choosept_lng": "-71.0588801",
        "therapyfinder_location": "Boston, MA",
    },
    "dc": {
        "label": "Washington, DC / DMV",
        "state": "DC",
        "search_terms": [
            "physical therapy Washington DC",
            "cash pay physical therapy DC",
            "out of network physical therapy Northern Virginia",
            "direct access physical therapy Maryland",
        ],
        "choosept_location": "Washington, DC",
        "choosept_lat": "38.9071923",
        "choosept_lng": "-77.0368707",
        "therapyfinder_location": "Washington, DC",
    },
    "minneapolis": {
        "label": "Minneapolis, MN",
        "state": "MN",
        "search_terms": [
            "physical therapy Minneapolis MN",
            "cash pay physical therapy Minneapolis",
            "out of network physical therapy Minneapolis",
            "direct access physical therapy Twin Cities",
        ],
        "choosept_location": "Minneapolis, MN",
        "choosept_lat": "44.977753",
        "choosept_lng": "-93.2650108",
        "therapyfinder_location": "Minneapolis, MN",
    },
    "denver": {
        "label": "Denver / Boulder, CO",
        "state": "CO",
        "npi_city": "Denver",       # exact city name for NPI Registry queries
        "search_terms": [
            "physical therapy Denver CO",
            "cash pay physical therapy Denver",
            "out of network physical therapy Boulder CO",
            "direct access physical therapy Colorado",
        ],
        "choosept_location": "Denver, CO",
        "choosept_lat": "39.7392358",
        "choosept_lng": "-104.984853",
        "therapyfinder_location": "Denver, CO",
    },
    "bay_area": {
        "label": "Bay Area, CA",
        "state": "CA",
        "npi_city": "San Francisco",  # exact city name for NPI Registry queries
        "search_terms": [
            "physical therapy San Francisco CA",
            "cash pay physical therapy Bay Area",
            "out of network physical therapy Oakland CA",
            "direct access physical therapy Silicon Valley",
        ],
        "choosept_location": "San Francisco, CA",
        "choosept_lat": "37.7749295",
        "choosept_lng": "-122.4194155",
        "therapyfinder_location": "San Francisco, CA",
    },
}

# Keywords that signal a cash-pay / out-of-network practice
CASH_PAY_KEYWORDS = [
    "no insurance",
    "cash based",
    "cash-based",
    "cash pay",
    "cash-pay",
    "cash only",
    "cash and carry",
    "out of network",
    "out-of-network",
    "out of pocket",
    "oon provider",
    "direct access",
    "direct pay",
    "direct-pay",
    "direct care",
    "self pay",
    "self-pay",
    "private pay",
    "no insurance needed",
    "no insurance required",
    "we do not accept insurance",
    "we do not bill insurance",
    "does not accept insurance",
    "insurance free",
    "without insurance",
    "fee for service",
    "transparent pricing",
    "transparent price",
    "flat fee",
    "flat rate",
    "no contracts",
    "concierge physical therapy",
    "boutique physical therapy",
    "membership based",
    "membership-based",
    "1:1 care",
    "1-on-1",
    "one on one care",
    "one-on-one care",
    "undivided attention",
    "dedicated one-on-one",
]

SPORTS_KEYWORDS = [
    "sports",
    "sport ",
    "athlete",
    "athletic",
    "performance",
    "running",
    "runner",
    "cycling",
    "triathlon",
    "triathlete",
    "swimming",
    "basketball",
    "football",
    "baseball",
    "soccer",
    "tennis",
    "golf",
    "crossfit",
    "weightlifting",
    "powerlifting",
    "strength and conditioning",
    "sport-specific",
    "sports rehab",
    "sports medicine",
    "sport performance",
    "return to sport",
]

ORTHO_KEYWORDS = [
    "orthopedic",
    "orthopaedic",
    "ortho",
    "musculoskeletal",
    "spine",
    "spinal",
    "back pain",
    "neck pain",
    "shoulder",
    "knee",
    "hip replacement",
    "ankle",
    "post-surgical",
    "post surgical",
    "post-op",
    "acl",
    "rotator cuff",
    "manual therapy",
    "joint replacement",
    "fracture",
    "injury rehab",
    "musculoskeletal rehab",
]

PELVIC_KEYWORDS = [
    "pelvic floor",
    "pelvic health",
    "pelvic PT",
    "pelvic physical therapy",
    "women's health",
    "womens health",
    "prenatal",
    "postnatal",
    "postpartum",
    "maternal health",
    "bladder",
    "incontinence",
    "diastasis",
    "prolapse",
    "pelvic pain",
    "pregnancy physical therapy",
    "obstetric",
    "gynecologic",
    "vulvodynia",
    "interstitial cystitis",
    "endometriosis",
]

# Playwright / HTTP settings
REQUEST_TIMEOUT = 15  # seconds for HTTP requests
MAPS_SCROLL_PAUSES = 4  # how many times to scroll the Maps results panel
MAPS_MAX_RESULTS = 40  # max listings to pull per search query
INTER_REQUEST_DELAY = (1.5, 3.0)  # (min, max) random delay seconds

DB_PATH = "pt_clinics.db"
